server:
  port: 8863
spring:
  application:
    name: nacos-service-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
service:
  hello:
    name: nacos-service
feign:
  hystrix:
    enabled: true

