#服务端口号
server:
  port: 8863

#服务名
spring:
  application:
    name: nacos-service-consumer
  #nacos注册地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#调用服务名称
service:
  hello:
    name: nacos-service

#开启hystrix断路器
feign:
  hystrix:
    enabled: true

#ribbon超时时间
ribbon:
    ReadTimeOut: 60000
    ConnectTimeOut: 60000

#前端访问端口
frontend:
  port: 9527

#hystrix配置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            #Hystrix默认超时时间是1秒，如果超出这个时间尚未做出反应，
            #就会进入fallback,由于Bean的装配和懒加载机制，Feign首次请求都会加载比较慢
            timeoutInMilliseconds: 5000
