server:
  port: 8763
spring:
  application:
    name: eureka-client
  data:
    mongodb:
      uri: mongodb://spring:123456@localhost:27017/spring
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
